services:
  # this is the Twingate connector that allows access into the Render private network.
  - type: worker
    name: twingate-connector
    branch: main
    env: docker
    dockerfilePath: ./twingate/Dockerfile
    dockerContext: ./twingate
    autoDeploy: false
    envVars:
      - key: TENANT_URL
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: REFRESH_TOKEN
        sync: false
      - key: TWINGATE_LOG_ANALYTICS
        value: "v1"
      - key: TWINGATE_LABEL_DEPLOYEDBY
        value: "render"
  # this is a stand-in for a private web service in your Render team
  - type: pserv
    name: twingate-private-service
    branch: main
    env: docker
    autoDeploy: false
    dockerFilePath: ./example-pserv/Dockerfile
    dockerContext: ./example-pserv

databases:
  - name: twingate-postgres
    plan: basic-256mb
    diskSizeGB: 1
